name: Spin2cpp CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_call:

jobs:
  build_win32:
    runs-on: ubuntu-20.04
    steps:
      - name: Install MinGW
        run: "sudo apt-get install gcc-mingw-w64-i686"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make zip
      - name: Rename ZIPs
        run: |
           mv flexptools.zip "flexptools-win32-`git describe --tags --always`.zip"
           mv spin2cpp.zip "spin2cpp-win32-`git describe --tags --always`.zip"
      - uses: actions/upload-artifact@v3
        with:
          name: release_zips_win32
          path: "./*.zip"
  test_offline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: test
        run: make test_offline
  test_spinsim:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: make
        run: make
      - name: test
        run: make test_spinsim

